# Generated by Django 3.0.4 on 2020-04-30 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOnHazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_user_name', models.CharField(max_length=100)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('garden_name', models.CharField(max_length=100)),
                ('report_status', models.CharField(default='Not yet addressed', max_length=100)),
                ('report_title', models.CharField(max_length=100)),
                ('report_text', models.CharField(max_length=300)),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
