pipeline {
   agent none
   stages {
       stage('Build') {
           agent {
               docker {
                   image 'python:3-alpine'
               }
           }
           steps {
               withEnv(["HOME=${env.WORKSPACE}"]) {
                   sh 'pip install django'
                   sh 'pip install pymysql'
                   sh 'pip install django-crispy-forms'
                   sh 'pip install django-phone-field'
                   //sh 'smartdogarden/manage.py runserver'
               }
           }
       }
       stage('Test') {
           agent {
               docker {
                   image 'python:3-alpine'
               }
           }
           steps {
               withEnv(["HOME=${env.WORKSPACE}"]) {
                   sh 'pip install django'
                   sh 'pip install pymysql'
                   sh 'pip install django-crispy-forms'
                   sh 'pip install django-phone-field'
                   sh 'python smartdogarden/manage.py test home'
               }
           }
       }
   }
}