pipeline {
    agent {
        docker {
            image 'python:3-alpine'
        }
    }
    stages {
        stage('Build') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django'
                    sh 'pip install pymysql'
                    sh 'pip install django-crispy-forms'
                    sh 'pip install django-phone-field'
                }
            }
        }
        stage('Test') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    //sh 'pip install django_jenkins'
                    //sh 'pip install \'coverage==4.5.4\''
                    //sh 'pip install pep8'
                    //sh 'pip install pyflakes'
                    //sh 'pip install pylint'
                    sh 'pip3 install --user -r requirements.txt'
                    sh 'cd smartdogarden && python manage.py jenkins home.tests_all --enable-coverage'
                }
            }
            post {
                always {
                    junit 'smartdogarden/reports/junit.xml'
                    recordIssues(
                        tool: pep8(pattern: 'smartdogarden/reports/pep8.report'),
                        unstableTotalAll: 400,
                        failedTotalAll: 400
                    )
                    recordIssues(
                        tool: pyLint(pattern: 'smartdogarden/reports/pylint.report'),
                        unstableTotalAll: 400,
                        failedTotalAll: 400
                    )
		    recordIssues(tools: [flake8(pattern: 'smartdogarden/reports/pyflakes.report')])
                }
          success {
             mail to: 'dev@smartdogarden.com',
                subject: "Status of pipeline: ${currentBuild.fullDisplayName}",
                body: "click here to for full view ${env.BUILD_URL}       has result ${currentBuild.result}       click this link to view the test results: ${BUILD_URL}/testReport"
          }
          failure {
             mail to: 'dev@smartdogarden.com',
                subject: "Status of pipeline: ${currentBuild.fullDisplayName}",
                body: "click here to for full view ${env.BUILD_URL}      has result${currentBuild.result}      click this link to view the test results: ${BUILD_URL}/testReport "
          }
            }
        }
    }
}

